---
server:
  port: 8888
    
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/isaachambers/ConfigurationProperties
          search-paths:
          - 'kenya*' 
          - 'feign*'
          - 'tanzania*' 
          - 'uganda*' 
          - 'congo*'
          - 'zimbabwe*'
          - 'customerservice*'
          - 'rwanda*'
  security:
    user:
      name: admin
      password: admin
      